"""initial schema

Revision ID: bf13d07dbb2d
Revises: 
Create Date: 2026-01-16 12:30:03.063454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf13d07dbb2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('crop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmis_crop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_amharic', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('crop_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_crop_category', 'crops', ['category'], unique=False)
    op.create_index('idx_crop_name', 'crops', ['name'], unique=False)
    op.create_index('idx_crop_name_amharic', 'crops', ['name_amharic'], unique=False)
    op.create_index('idx_crop_name_lower', 'crops', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('livestock',
    sa.Column('livestock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nmis_livestock_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_amharic', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('livestock_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_livestock_category', 'livestock', ['category'], unique=False)
    op.create_index('idx_livestock_name', 'livestock', ['name'], unique=False)
    op.create_index('idx_livestock_name_amharic', 'livestock', ['name_amharic'], unique=False)
    op.create_index('idx_livestock_name_lower', 'livestock', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('marketplaces',
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_amharic', sa.String(length=255), nullable=True),
    sa.Column('marketplace_type', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('region_amharic', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("marketplace_type IN ('crop', 'livestock')", name='ck_marketplace_type'),
    sa.PrimaryKeyConstraint('marketplace_id')
    )
    op.create_index('idx_marketplace_coords', 'marketplaces', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_marketplace_name', 'marketplaces', ['name'], unique=False)
    op.create_index('idx_marketplace_name_amharic', 'marketplaces', ['name_amharic'], unique=False)
    op.create_index('idx_marketplace_name_lower', 'marketplaces', [sa.literal_column('lower(name)')], unique=False)
    op.create_index('idx_marketplace_region', 'marketplaces', ['region'], unique=False)
    op.create_index('idx_marketplace_type', 'marketplaces', ['marketplace_type'], unique=False)
    op.create_table('scraper_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scraper_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('started', 'success', 'partial', 'failed')", name='ck_scraper_status'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_scraper_started', 'scraper_logs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index('idx_scraper_status', 'scraper_logs', ['status'], unique=False)
    op.create_index('idx_scraper_type', 'scraper_logs', ['scraper_type'], unique=False)
    op.create_table('crop_varieties',
    sa.Column('variety_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('nmis_variety_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_amharic', sa.String(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.crop_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variety_id'),
    sa.UniqueConstraint('crop_id', 'name', name='uq_crop_variety')
    )
    op.create_index('idx_variety_crop', 'crop_varieties', ['crop_id'], unique=False)
    op.create_index('idx_variety_name', 'crop_varieties', ['name'], unique=False)
    op.create_index('idx_variety_nmis_id', 'crop_varieties', ['nmis_variety_id'], unique=False)
    op.create_table('livestock_breeds',
    sa.Column('breed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livestock_id', sa.Integer(), nullable=False),
    sa.Column('nmis_breed_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_amharic', sa.String(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.livestock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('breed_id'),
    sa.UniqueConstraint('livestock_id', 'name', name='uq_livestock_breed')
    )
    op.create_index('idx_breed_livestock', 'livestock_breeds', ['livestock_id'], unique=False)
    op.create_index('idx_breed_name', 'livestock_breeds', ['name'], unique=False)
    op.create_index('idx_breed_nmis_id', 'livestock_breeds', ['nmis_breed_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('variety_id', sa.Integer(), nullable=True),
    sa.Column('livestock_id', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('modal_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('(crop_id IS NOT NULL AND livestock_id IS NULL) OR (crop_id IS NULL AND livestock_id IS NOT NULL)', name='ck_price_crop_or_livestock'),
    sa.ForeignKeyConstraint(['breed_id'], ['livestock_breeds.breed_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.crop_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.livestock_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.marketplace_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variety_id'], ['crop_varieties.variety_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('price_id'),
    sa.UniqueConstraint('marketplace_id', 'crop_id', 'variety_id', 'price_date', name='uq_crop_market_price'),
    sa.UniqueConstraint('marketplace_id', 'livestock_id', 'breed_id', 'price_date', name='uq_livestock_market_price')
    )
    op.create_index('idx_price_breed', 'market_prices', ['breed_id'], unique=False)
    op.create_index('idx_price_crop', 'market_prices', ['crop_id'], unique=False)
    op.create_index('idx_price_crop_lookup', 'market_prices', ['marketplace_id', 'crop_id', sa.literal_column('price_date DESC')], unique=False)
    op.create_index('idx_price_date', 'market_prices', [sa.literal_column('price_date DESC')], unique=False)
    op.create_index('idx_price_fetched', 'market_prices', [sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index('idx_price_livestock', 'market_prices', ['livestock_id'], unique=False)
    op.create_index('idx_price_livestock_lookup', 'market_prices', ['marketplace_id', 'livestock_id', sa.literal_column('price_date DESC')], unique=False)
    op.create_index('idx_price_marketplace', 'market_prices', ['marketplace_id'], unique=False)
    op.create_index('idx_price_variety', 'market_prices', ['variety_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_variety', table_name='market_prices')
    op.drop_index('idx_price_marketplace', table_name='market_prices')
    op.drop_index('idx_price_livestock_lookup', table_name='market_prices')
    op.drop_index('idx_price_livestock', table_name='market_prices')
    op.drop_index('idx_price_fetched', table_name='market_prices')
    op.drop_index('idx_price_date', table_name='market_prices')
    op.drop_index('idx_price_crop_lookup', table_name='market_prices')
    op.drop_index('idx_price_crop', table_name='market_prices')
    op.drop_index('idx_price_breed', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index('idx_breed_nmis_id', table_name='livestock_breeds')
    op.drop_index('idx_breed_name', table_name='livestock_breeds')
    op.drop_index('idx_breed_livestock', table_name='livestock_breeds')
    op.drop_table('livestock_breeds')
    op.drop_index('idx_variety_nmis_id', table_name='crop_varieties')
    op.drop_index('idx_variety_name', table_name='crop_varieties')
    op.drop_index('idx_variety_crop', table_name='crop_varieties')
    op.drop_table('crop_varieties')
    op.drop_index('idx_scraper_type', table_name='scraper_logs')
    op.drop_index('idx_scraper_status', table_name='scraper_logs')
    op.drop_index('idx_scraper_started', table_name='scraper_logs')
    op.drop_table('scraper_logs')
    op.drop_index('idx_marketplace_type', table_name='marketplaces')
    op.drop_index('idx_marketplace_region', table_name='marketplaces')
    op.drop_index('idx_marketplace_name_lower', table_name='marketplaces')
    op.drop_index('idx_marketplace_name_amharic', table_name='marketplaces')
    op.drop_index('idx_marketplace_name', table_name='marketplaces')
    op.drop_index('idx_marketplace_coords', table_name='marketplaces')
    op.drop_table('marketplaces')
    op.drop_index('idx_livestock_name_lower', table_name='livestock')
    op.drop_index('idx_livestock_name_amharic', table_name='livestock')
    op.drop_index('idx_livestock_name', table_name='livestock')
    op.drop_index('idx_livestock_category', table_name='livestock')
    op.drop_table('livestock')
    op.drop_index('idx_crop_name_lower', table_name='crops')
    op.drop_index('idx_crop_name_amharic', table_name='crops')
    op.drop_index('idx_crop_name', table_name='crops')
    op.drop_index('idx_crop_category', table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
